<?php

use App\Movie;
use App\Price\RegularPrice;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-23 at 22:53:11.
 */
class RegularTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RegularPrice
     */
    protected $regularPrice;

    /**
     * @var int
     */
    protected $dayRented;

    protected function setUp()
    {
        $this->regularPrice = new RegularPrice;
    }

    /**
     * @test
     *
     */
    public function testGetPriceCode()
    {
        $this->assertSame(Movie::REGULAR, $this->regularPrice->getPriceCode());
    }

    /**
     * @test
     *
     */
    public function testGetCharge()
    {
        // レンタル泊数が２日以下の場合
        $this->dayRented = 2;
        $expected_within2days = 2;
        $this->assertEquals($expected_within2days, $this->regularPrice->getCharge($this->dayRented));

        // レンタル泊数が３日以上の場合
        $this->dayRented = 3;
        $result = 2;
        $expectedOver2days = ($this->dayRented - 2) * 1.5 + $result;
        $this->assertEquals($expectedOver2days, $this->regularPrice->getCharge($this->dayRented));
    }
}
